### ISSUE TITLE
saveAction not being called

### ISSUE THREAD

**Issue by baron1405** [shipshapecode/ember-x-editable#130]
I have been trying to get my saveAction handler function called but have been unable to get it to work. So I decided to verify that the ember-x-editable demo outputs the save message to the console. It does not. So I think something is wrong with saveAction (and probably cancelAction).

Ember 3.1.3
Ember-x-editable 0.5.0
Chrome 66
CentOS 7.5

**Comment by rwwagner90** [comment]
@baron1405 it seems I forgot to update the docs to move the actions, when we moved to contextual components. Passing them to the inner component should work:

```
{{#ember-x-editable
fontFamilyConfig=fontFamilyConfig
isFieldEditing=isFieldEditing
validator=textValidator
value='TestString' as |x|}}
  {{x.text
    cancelAction=(action 'cancelAction')
    saveAction=(action 'saveAction')
  }}
{{/ember-x-editable}}
```

**Comment by baron1405** [comment]
Thanks, that worked! One remaining question is how do I get the selected value from within the saveAction handler?

**Comment by rwwagner90** [comment]
The value is not passed to the save action, currently. `value` is just updated with a two way binding. Do you need it in the save action?

**Comment by baron1405** [comment]
Yes, it would be very convenient.

**Comment by rwwagner90** [comment]
@baron1405 yes, `value` is a two way binding, that is always updated.

```
{{#ember-x-editable
fontFamilyConfig=fontFamilyConfig
isFieldEditing=isFieldEditing
validator=textValidator
value=valueYouWant as |x|}}
  {{x.text
    cancelAction=(action 'cancelAction')
    saveAction=(action 'saveAction')
  }}
{{/ember-x-editable}}
```

In the above example, you can then access with `valueYouWant` in the template or component where you are using this. The value is just always bound to the variable you set it to with a two way binding.

Can you not use the variable directly for some reason? I know it is bad DDAU, but it should still work.

**Comment by baron1405** [comment]
Got it and that will work fine for me. You might consider adding this to the README since it was not obvious to me. Once again, thanks for the quick response and help!

**Comment by rwwagner90** [comment]
We should probably refactor this to use DDAU anyway. It would not be too difficult. Would you be interested in submitting a PR for that?

**Comment by baron1405** [comment]
I'm still pretty new to Ember and front-end development (been primarily doing back-end). What is considered the best practice for this kind of thing?

**Comment by rwwagner90** [comment]
DDAU is the best practice, but this addon was written a long time ago, before those standards were really the standard, so it could use some updating.

**Comment by baron1405** [comment]
So assigning to the value is good (i.e. Data Down) but the change of state should trigger an action. That sounds like the saveAction should pass the new value as an argument. The bidirectional binding of value could remain for compatibility, at least for a while. Is that close to a correct assessment?

**Comment by rwwagner90** [comment]
Yep, that sounds correct to me, although, I would just go ahead and remove the two way binding for value, and set value with the action.

**Comment by baron1405** [comment]
Then how does the user of the component access the value?

**Comment by baron1405** [comment]
Currently, with the two-way binding, I am passing the value as an action argument to my saveAction by doing the following:
```
{{#ember-x-editable
value=valueYouWant as |x|}}
  {{x.text
    saveAction=(action 'saveAction' valueYouWant)
  }}
{{/ember-x-editable}}
```
How would this work in the refactored world?

**Comment by rwwagner90** [comment]
Your `saveAction` is passed the value, that is the AU part of DDAU. You then would set the variable you have passed to `value` to that new value, to ensure the component is updated when the action fires.

**Comment by baron1405** [comment]
Cool. So the changes to this project come down to removing the bi-directional binding and passing the value to the save action.

**Comment by rwwagner90** [comment]
Yes, essentially. It's bound automatically by ember, so we would have to pass with `(readonly value)` then update `value` via the actions.

**Comment by baron1405** [comment]
I am on vacation for the next week and a half but can look into this when I return unless you get to it beforehand.

**Comment by rwwagner90** [comment]
It's a very quick thing to change. I can do it.
