### ISSUE TITLE
pods and Assertion Failed: A component or helper named "ember-x-editable" could not be found

### ISSUE THREAD

**Issue by yaxinr** [shipshapecode/ember-x-editable#142]
I use [podmoduleprefix](https://cli.emberjs.com/release/advanced-use/project-layouts/#podmoduleprefix) and your components don work.
[**Addons should only use the classic structure for compatibility with either classic or pods-based consuming applications**](https://cli.emberjs.com/release/advanced-use/project-layouts/#classiclayout)

**Comment by rwwagner90** [comment]
I would recommend not using `podmoduleprefix`. Is it a requirement for your app?

**Comment by yaxinr** [comment]
> I would recommend not using `podmoduleprefix`. Is it a requirement for your app?

ergonomic requirements, because of many models and routes

**Comment by rwwagner90** [comment]
@yaxinr you can use pods without a `podModulePrefix`. I would highly recommend doing that. You can use classic layout for models and routes, rather than pods.
