### ISSUE TITLE
App is breaking after using npm i ember-x-editable

### ISSUE THREAD

**Issue by Darshan-Chauhan** [shipshapecode/ember-x-editable#35]
After installing ember-x-editable , I got following error.

`_DOMException: Failed to execute 'setAttribute' on 'Element': '}}' is not a valid attribute name._`

I also tried using bower, than it was giving error that 'ember-resolver' module not found.

Could you look into that?

**Comment by rwwagner90** [comment]
@Darshan-Chauhan you install ember addons with `ember install`. Try `ember install ember-x-editable`
